#!/bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1 # bspwm doesn't play nice with java

sxhkd &
$HOME/.config/bin/compton &
$HOME/.config/bin/bspwm-configure-desktops &

bspc config border_width	2
bspc config window_gap		20

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config click_to_focus	true
bspc config remove_disabled_monitor true

bspc rule -a mpv state=floating
bspc rule -a firefox* state=tiled

$HOME/.config/polybar/launch.sh
$HOME/bin/autostart.sh
