#!/bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1 # bspwm doesn't play nice with java

# split 10 desktops evenly accross monitors (rounding down)
bspc wm -O eDP-1 DP-2 DP-3
i=1
n=$(bspc query -M | wc -l)
per=$(( 10 / n ))
for m in $(bspc query -M); do
	bspc monitor "$m" -d $(seq -s ' ' "$i" $(( i + per - 1 )))
	i="$(( i + per ))"
done

bspc config border_width	2
bspc config window_gap		40

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

#bspc config click_to_focus	true
#bspc config remove_disabled_monitor true

# window rules
bspc rule -a mpv state=floating
bspc rule -a firefox* state=tiled

# Startup
"$HOME"/.config/bin/bar &
sxhkd &
dunst &
picom --experimental-backends &
