#! /bin/sh

# polybar
primary_monitor=$(xrandr | grep " connected" | sort -k3 -n | head -1 | cut -d ' ' -f1)
wlan_dev=$(ip link show | sed -E 's/^[0-9]+: (wl.*):.*/\1/;tx;d;:x;q')
eth_dev=$(ip link show | sed -E 's/^[0-9]+: (en.*):.*/\1/;tx;d;:x;q')
MONITOR=$primary_monitor WLAN=$wlan_dev ETH=$eth_dev polybar topbar &

sxhkd &
compton --config ~/.config/compton.conf -b &
~/bin/configure-desktops &

bspc config border_width	0
bspc config window_gap		20

bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

bspc config click_to_focus	true
bspc config remove_disabled_monitor true
